### ISSUE TITLE
encoding of the '!important' rule

### ISSUE THREAD

**Issue by pglatza** [le-tex/CSSa#1]
For a following [idml2xml](https://github.com/transpect/idml2xml) commit I need to know how to save the `!important` CSS rule in Hub. 

The following image will demonstrate the need on setting cell border properties with an important rule: ![cell-borders](https://cloud.githubusercontent.com/assets/373153/12086381/f5f28e20-b2c9-11e5-9b75-deddf5b09a80.png)
Cell 1 has a solid border, tough cell 2 (below cell 1) overwrites the border-bottom property of cell 1.

**Idea A**
We expand all attribute value definitions to allow `!important` as suffix:

```
    css:border-top-width="0.5pt !important"
    css:border-top-color="yellow !important"
```

**Idea B**
We use separate attributes: 

```
    css:border-top-color-important="true"
    css:border-top-width-important="true"
```

Leads to a lot of / inefficient attributes if there are lot of overwrites (i.e. dashed line, etc.).

**Idea C**
One attribute with a space separated list of the important properties:

```
    css:border-top-important="color width"
```

I would prefer idea C. Does this concept work for all CSS properties (what about single props, such as `css:color`)?

Any other suggestions?

**Comment by gimsieke** [comment]
I think we should go with Idea A and adapt the CSSa schema accordingly.

**Comment by gimsieke** [comment]
Con: It requires some more parsing when not using the [CSS parser](https://github.com/transpect/css-tools/blob/master/xsl/css-parser.xsl). 
Pro: It will be parsed as expected by said CSS parser.

**Comment by pglatza** [comment]
Actually, there is no need for the `!important` suffix at the moment. Resolved in idml2xml without of setting `!important` anywhere.

Another aspect to mention: `!important` is useless in HTML context, when the border-width of the cell is thinner than the neighbor as in the following example:

```
<html xmlns="http://www.w3.org/1999/xhtml">
<table border="1" style="border-collapse:collapse">
  <tr>
    <td style="border:3px solid black">1</td>
    <td style="border:2px solid red">2</td>
  </tr>
</table></html>
```

By adding `!important` to the second cell there will be no change of the border style between cell 1 and cell 2.
